# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os: 
  - linux
  - osx
  
sudo: true
cache: packages

r:
- oldrel
- release
- devel

matrix:
  allow_failures:
  - r: devel

before_script:
- java -version
- echo PATH=$PATH
- echo JAVA_HOME=$JAVA_HOME

after_success:
- Rscript -e 'covr::codecov()'
